package com.hireguard.model.mongodb;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.FieldType;

import java.time.Instant;
import java.util.List;

/**
 * MongoDB Document Entity: TrustReport
 * Stores immutable snapshots of calculated employer trust scores, assigned risk tiers,
 * and comprehensive explanations generated by graph and NLP risk scans.
 */
@Document(collection = "trust_reports")
public class TrustReport {

    @Id
    private String id;

    @Indexed
    private String companyId;

    private Double trustScore;

    @Field(targetType = FieldType.STRING)
    private RiskLevel riskLevel;

    private List<String> reasons;

    private List<String> graphRiskFactors;

    @CreatedDate
    private Instant generatedAt;

    public enum RiskLevel {
        CRITICAL_RISK,
        HIGH_RISK,
        MODERATE_RISK,
        LOW_RISK,
        TRUSTED
    }

    public TrustReport() {
    }

    public TrustReport(String id, String companyId, Double trustScore, RiskLevel riskLevel, List<String> reasons, List<String> graphRiskFactors) {
        this.id = id;
        this.companyId = companyId;
        this.trustScore = trustScore;
        this.riskLevel = riskLevel;
        this.reasons = reasons;
        this.graphRiskFactors = graphRiskFactors;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCompanyId() {
        return companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public Double getTrustScore() {
        return trustScore;
    }

    public void setTrustScore(Double trustScore) {
        this.trustScore = trustScore;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public List<String> getReasons() {
        return reasons;
    }

    public void setReasons(List<String> reasons) {
        this.reasons = reasons;
    }

    public List<String> getGraphRiskFactors() {
        return graphRiskFactors;
    }

    public void setGraphRiskFactors(List<String> graphRiskFactors) {
        this.graphRiskFactors = graphRiskFactors;
    }

    public Instant getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(Instant generatedAt) {
        this.generatedAt = generatedAt;
    }

    @Override
    public String toString() {
        return "TrustReport{" +
                "id='" + id + '\'' +
                ", companyId='" + companyId + '\'' +
                ", trustScore=" + trustScore +
                ", riskLevel=" + riskLevel +
                ", generatedAt=" + generatedAt +
                '}';
    }
}
